### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Koeng101** [Koeng101/dnadesign#8]
Some various todos while in a very unstable period for DNA design.

- [ ] Rewrite contribution docs
- [ ] Rewrite top level package docs
- [ ] Rewrite tutorials package
- [x] Reduce dependencies

**Comment by Koeng101** [comment]
I don't feel the need to do any of these, actually. I think tutorials in the form of lua with the docs site and with python will be way more interesting for people using this software. So I'm closing this as an enhancement.
